{% set name = "shutilwhich-cwdpatch" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6ab900b532b9651b23780301a23e6e330c14076208b0c56300e09cc573a3546d

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - shutilwhich_cwdpatch

about:
  home: https://github.com/kiwi0fruit/shutilwhich-cwdpatch
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Patch for shutil.which and shutilwhich that disables search in CWD on Windows."
  doc_url: https://github.com/kiwi0fruit/shutilwhich-cwdpatch
  dev_url: https://github.com/kiwi0fruit/shutilwhich-cwdpatch

extra:
  recipe-maintainers:
    - kiwi0fruit
